version: "3"

networks:
  webnet:
    driver: bridge

services:
  server: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet
    image: server:0.0.1

  prometheus:
    image: prom/prometheus:v2.40.7
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webnet

  grafana:
    image: grafana/grafana:9.4.2
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - webnet
